config/routes.rb
Blog::Application.routes.draw do

  root :to => 'posts#show'

  devise_for :users do
      resources :comments
    end

  resources :posts do
      resources :comments
  end

  resources :comments
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :manage, Comment, :user_id => user.id
      # can :edit, Comment, :user_id => user.id
      # can :delete, Comment, :user_id => user.id
      can :read, Comment
      can :read, Post, :publish => true
      can :create, Comment
    end
  end
end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/bryanrite/cancancan/wiki/Defining-Abilities

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  has_attached_file :image, :styles => { :large => "450x450>", :medium => "300x300>"}, :validates_attachment_content_type => :image, :content_type => /\Aimage\/.*\Z/
  validates :title, presence: true
  validates :image, :attachment_presence => true
  validates_attachment_content_type :image, :content_type => /\Aimage/

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :send_welcome_message #, other callbacks..

 def send_welcome_message
  UserMailer.signup_confirmation(self).deliver
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def index
    @comments = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      # flash[:notice] = "New comment created."
      respond_to do |format|
        format.html { redirect_to post_path(@comment.post_id) }
        format.js
      end
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def edit
    @comment = Comment.find(params[:id])
    @post = Post.find(@comment.post_id)
  end

  def update
    @comment = Comment.find(params[:id])
    # @post = Post.find(params[:comment][:post_id])
    if @comment.update(comment_params)
      flash[:notice]="Comment updated."
      render :js => "window.location = '/posts/#{@comment.post_id}'"
    else
      render 'edit'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    id = @comment.post_id
    @comment.destroy
    flash[:notice] = "Comment deleted."
    redirect_to post_path(@comment.post_id)
  end

private

  def comment_params
    params.require(:comment).permit(:date, :body, :post_id, :name, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post created."
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def show
    if (params[:id]) == nil
      @post = Post.where(publish: true).order('id DESC').first
      @comment = Comment.new
    else
      @comment = Comment.new
      @post = Post.find(params[:id])
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post updated."
      redirect_to post_path(@post)
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Post deleted."
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :date, :body, :image, :date, :publish)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<% time = comment.date %>
<strong><%= comment.name %></strong> said <%= time.strftime("on %B %e, %Y") %>

<% if can? :edit, comment %>
  <%= link_to "update", edit_post_comment_path(comment.post, comment), :class => "btn-xs btn-warning" %>
<% end %>

<% if can? :delete, comment %>
  <%= link_to "delete", post_comment_path(comment.post, comment), :class => "btn-xs btn-danger", method: :delete %>
<% end %>

<p><%= comment.body %></p>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment], :html => { :id => 'comment_form' }, remote: true do |f| %>
<%= f.hidden_field :user_id, :value => current_user.id %>
<%= f.hidden_field :post_id, :value => @post.id %>
<%= f.label :name %><br>
<%= f.text_field :name, :value => current_user.name,:readonly => true %><br>
<%= f.hidden_field :date, :value => Time.now %><br>
<%= f.label :comment %><br>
<%= f.text_area :body, :cols => "60", :rows => "4" %><br>
<%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/comments/create.js.erb
$('#comments_list').append('<%= j render("comments/comment", :comment => @comment) %>');
$("#comment_form")[0].reset();
// @comment = "comments/comment", :comment => @comment

app/views/comments/edit.html.erb
<h4>Edit Comment</h4>

<%= render 'form' %>

app/views/comments/new.js.erb
$('<%= j render "form" %>')

app/views/layouts/_errors.html.haml
- if object.errors.any?
  .error_messages
    %h2 Form is invalid
    %ul
      - object.errors.full_messages.each do |message|
        %li= message 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
      <%= link_to image_tag("ruby3.png", :id => 'ruby', :height => '25px', :class => "navbar-text navbar-left"), root_url %>
      <%= link_to "Ruby Newbie", root_url, :class => "navbar-brand" %>
      <%= link_to "All Posts", posts_path, :class => "navbar-text navbar-left" %>
      <%= link_to "About", page_path('about'), :class => "navbar-text navbar-left" %>
      <% if can? :create, @post %>
        <%= link_to "New Post", new_post_path, :class => "navbar-text navbar-left" %>
      <% end %>
    </div>

    <div class="pull-right">
      <% if user_signed_in? %>
        <span id="login">Logged in as <strong><%= current_user.email %></strong><span>
        <%= link_to 'Edit profile', edit_user_registration_path, :class => "btn btn-default navbar-btn" %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "btn btn-default navbar-btn" %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => "btn btn-default navbar-btn"%>
        <%= link_to "Login", new_user_session_path, :class => "btn btn-default navbar-btn" %>
      <% end %>
    </div>
  </div>

    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
        <% elsif flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
        <% end %>

      <%= yield %>
    </div>
</body>
</html>

app/views/pages/about.html.haml
%h3 About

= image_tag 'nathananne.jpg', height: 350, alt: "Anne and Nathan", id: "about"

.about-text
	%p Hi, my name is Nathan and I built this blog with Ruby on Rails. It uses Devise for authentication, CanCan for authorization, Paperclip for image uploads, Action Mailer to welcome new users, and Ajax to add and remove comments. Views are built in a combination of html, haml and Bootstrap.
	%p Before becoming a web developer, I worked in public health. I had the opportunity to advocate for strong public policies to prevent and control cancer and to reduce the impact of harmful substances like tobacco. I saw real progress in these areas, but I also felt that much more could be done. 
	%p I started looking for new tools that could be used alongside traditional approaches. I am especially interested in how existing, pervasive technologies - such as web and mobile apps, scanners and wireless devices - can be used alone and in concert to promote health and control disease. Ultimately, this led me to my present work. I am currently part of one team that is building an online marketplace for health services and another that is developing a mobile app to promote physical activity throughout the day.
	%p My wife Anne and I live in Portland with our dog Raja. Anne works at Concordia University. Raja mostly chases squirrels.
	More about Nathan at 
	=link_to "LinkedIn", "http://www.linkedin.com/in/nathangrey/"
	%span: and 
	=link_to " GitHub", "https://github.com/nngrey"
	%span> .
	

app/views/posts/_form.html.haml
= render 'layouts/errors', :object => @post 

= form_for @post, :html => { :multipart => true } do |f| 
  = f.label :title, "Title"
  = f.text_field :title
  %br/
  = f.label :date, "Date"
  = f.datetime_field :date, :value => Date.today
  %br/
  = f.label :body, "Body"
  = f.text_area :body, :cols => "100", :rows => "20"
  %br/
  = f.label :image, 'Image'
  = f.file_field :image
  = f.label :publish, 'Post status'
  %br/
  = f.radio_button :publish, false
  = label :publish, 'Edit'
  = f.radio_button :publish, true
  = label :publish, 'Published'
  %br/
  = f.submit(:class => 'btn btn-primary')

app/views/posts/edit.html.haml
%h4 Edit Post
= render 'form'

app/views/posts/index.html.haml
%h1 Posts

- @posts.each do |post|
  %br
  - if can? :read, post
    %span.list-title= link_to post.title, post_path(post)
    - time = post.date
    %span>= time.strftime(", %B, %e %Y")
    %em= post.publish ? "" : " - unpublished"

app/views/posts/new.html.haml
%h1 New Post
= render 'form'

app/views/posts/show.html.haml
- if @post != nil
  %h4= @post.title
  - time = @post.date
  = time.strftime("Published on %B, %e %Y")
  %div= image_tag @post.image.url(:large), id: "post_image"
  %p= simple_format (@post.body)
  - if can? :update, @post
    = link_to "edit", edit_post_path(@post), :class => "btn btn-primary"
  - if can? :destroy, @post
    = link_to "delete", post_path(@post), data: { confirm: 'Are you sure?'}, |
      method: 'delete',                                                      |
      :class => "btn btn-danger"                                             |
  %hr/
  - if current_user != nil
    %h4 Add a comment
    = render 'comments/form'
  - else
    %span#login-link= link_to "Login", new_user_session_path
    = "to post a comment"
  - if @post.comments.length > 0
    %h4 Comments
    #comments_list
      - @post.comments.each do |comment|
        = render comment